version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  build:
    jobs:
      - cypress/run:
          post-steps:
            - run: 
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge cypress/reports/mocha/*.json > mochareports/report.json 
            - run: 
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - run:
                when: always
                name: Slack report
                command: npx cypress-slack-reporter --verbose
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/reports
          
#   nightly:
#     triggers: #use the triggers key to indicate a scheduled build
#       - schedule:
#           cron: "0 0 * * *" # use cron syntax to set the schedule
#           filters:
#             branches:
#               only:
#                 - add-cypress
    jobs:
      - cypress/run:
          post-steps:
            - run: 
                when: always
                name: Merge MochaAwesome Reports
                command: npx mochawesome-merge cypress/reports/mocha/*.json > mochareports/report.json 
            - run: 
                when: always
                name: Create mochawesome html report
                command: npx marge mochareports/*.json -f report -o mochareports
            - run:
                when: always
                name: Slack report
                command: npx cypress-slack-reporter --verbose
            - store_artifacts:
                path: mochareports
            - store_test_results:
                path: cypress/results
         
